<?php

namespace AppBundle\Entity;

/**
 * SensorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorRepository extends \Doctrine\ORM\EntityRepository
{
	public function __construct($sensor)
    {
        //parent::__construct();
        // your own logic
    }


	public function findByUser($sensor)
	{
	
		return $query = $this->createQueryBuilder('
			SELECT p from AppBundle:Wei p
			WHERE p.customer = :customer
			ORDER BY p.nickname
			')
			-> setParameter('customer', $sensor->getWeiwei()->getCustomercustomer());
	}
}
