AppBundle\Entity\ModweiStatus:
    type: entity
    table: ModWei_Status
    uniqueConstraints:
        Description_UNIQUE:
            columns:
                - Description
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: Description
    lifecycleCallbacks: {  }
