AppBundle\Entity\Pais:
    type: entity
    table: Pais
    uniqueConstraints:
        nombrePais_UNIQUE:
            columns:
                - nombrePais
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombrepais:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: nombrePais
    lifecycleCallbacks: {  }
