<?php

namespace AppBundle\Entity;

/**
 * WeiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeiRepository extends \Doctrine\ORM\EntityRepository
{
	public function findWeiCustomer($sensor)
	{
		
		$em = $this->getEntityManager();
		$query = $em->createQueryBuilder()
			->select('a')
			->from('AppBundle:Wei', 'a')
			->where('a.customer = :customerId')
			->setParameter('customerId', $sensor->getWeiwei()->getCustomer())
			->orderby ('a.nickname', 'ASC')
			;
		return $query;
	}
}
