fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

auth:
    resource: "@AuthBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
