app_sensor:
    resource: "@AppBundle/Controller/SensorController.php"
    type:     annotation

app_customer:
    resource: "@AppBundle/Controller/CustomerController.php"
    type:     annotation

auth:
    resource: "@AuthBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"